### PR TITLE
feat: show repo migration (go-ipfs 0.12.0)

### LINKED ISSUE #1823: Add meaningful GUI error when migration fails
Some power users may run into situation, where repo version is higher than one supported by ipfs-desktop:

```
021-05-13T22:01:23.422Z error: [ipfsd] start daemon Error: Initializing daemon...
go-ipfs version: 0.7.0
Repo version: 10
System version: amd64/windows
Golang version: go1.14.4
 
 Error: Your programs version (10) is lower than your repos (11).
Please update ipfs to a version that supports the existing repo, or run
a migration in reverse.
See https://github.com/ipfs/fs-repo-migrations/blob/master/run.md for details. 
 Command failed with exit code 1: D:\Users\foobar\AppData\Local\Programs\IPFS Desktop\resources\app.asar.unpacked\node_modules\go-ipfs\go-ipfs\ipfs.exe daemon --migrate --enable-gc --routing dhtclient
Error: Your programs version (10) is lower than your repos (11).
Please update ipfs to a version that supports the existing repo, or run
a migration in reverse.
See https://github.com/ipfs/fs-repo-migrations/blob/master/run.md for details.
```

IIUC this error lands in logs, but the user gets generic one with option to "restart" or "report github issue"
We should do better, and display console output to the user, so they can self-service.

### LINKED ISSUE #1940: Show repository migration progress in go-ipfs 0.12+
Ref. https://github.com/brave/brave-browser/issues/20106, https://github.com/ipfs/go-ipfs/issues/8344

- MVP in Desktop case would be to show window with startup log that contains migration progress.
- It should also detect migration errors like: https://github.com/ipfs/ipfs-desktop/issues/1823

### PR DESCRIPTION
**Pull request by hacdias**
Closes #1940 and closes #1823

Screenshot 2022-02-25 at 17 51 21

Screenshot 2022-02-25 at 17 50 51

### CODE REVIEW

**Comment by Carlos7687** [comment]
> _ No description provided. _
gh pr checkout 1982

**Review by Carlos7687 — APPROVED** [review]

**Comment by hacdias** [comment]
I will try to include #1823 in this PR too.

**Comment by hacdias** [comment]
@lidel can you please take a look? it should be ready

**Review by Mirage1348 — APPROVED** [review]

**Comment by lidel** [comment]
Added small fix that shows the migration window again after it is finished (so user who clicked "run in background" gets feedback when migration is finished and the IPFS node is running again): 

>

**Comment by lidel** [comment]
Added small fix that shows the migration window again after it is finished (so user who clicked "run in background" gets feedback when migration is finished and the IPFS node is running again): 

>

**Review by lidel — APPROVED** [review]
Thank you @hacdias!

Did some testing with 0.11 → 0.12 and UX should be more than enough for users with big repos.
Merging, as we want to ship ipfs-desktop with 0.12 this week.

**Comment by gRoussac** [comment]
Hi, just passing by to describe an issue I just had.

I installed the latest binary proposed go-ipfs_v0.11.0_linux-amd64.tar.gz and then wanted to have a look at the desktop version with ipfs-desktop-0.20.1-linux-amd64.deb which apparently installs v.0.12. 

Then trying to run daemon again I got  ` Your programs version (11) is lower than your repos (12)` 

Readme says `go get -u github.com/ipfs/fs-repo-migrations` but this failed with 

`package github.com/ipfs/fs-repo-migrations: no Go files in /home/greg/go/src/github.com/ipfs/fs-repo-migrations` 
I guess there is a path issue somewhere.

So I bascially deleted my config file and ipfs init again tu run go-ipfs version: 0.11.0 again.

Thanks

**Comment by hacdias** [comment]
Hi @gRoussac! IPFS Desktop upgraded your repository to a newer version. You now need to update the binary you are using to run IPFS from 0.11 to 0.12.

I created a PR to update the docs to the newer version: https://github.com/ipfs/ipfs-docs/pull/1074

**Comment by gRoussac** [comment]
Thanks!

**Pull request merged**
