### PR TITLE
fix: Refactor ctx

### LINKED ISSUE #1177: Refactor `ctx`
There is just one codebase that is run by one instance of the program at the time. Is it worth having a variable called `ctx` (context)? That'd certainly be more useful in HTTP (or any other protocol) handlers where each request is different.

While working on #1175 I found it a bit annoying to have to pass `ctx` around because I needed one single variable.

The idea is to remove `ctx` where possible and simply export the functions. Also, refactor the code so we don't have named and default exports on the same file as we do right now. That has been the cause for some bugs up until now.

### PR DESCRIPTION
**Pull request by SgtPooki**
`ctx` probably still needs some additional optimizations, but this is a significant improvement

May help with #2113

fixes #1177

### CODE REVIEW

**Comment by SgtPooki** [comment]
The failing workflow (`ci / test (macos-latest)`) runs correctly locally, so I am restarting that job

```
╰─ ✔ ❯ npm run test:e2e

> ipfs-desktop@0.20.5 test:e2e
> xvfb-maybe cross-env NODE_ENV=test playwright test test/e2e/launch.e2e.test.js


Running 10 tests using 1 worker

  ✓  test/e2e/launch.e2e.test.js:66:3 › A (5s)
  ✓  test/e2e/launch.e2e.test.js:80:3 › A (4s)
  ✓  test/e2e/launch.e2e.test.js:88:3 › A (4s)
  ✓  test/e2e/launch.e2e.test.js:109:3 ›  (4s)
  ✓  test/e2e/launch.e2e.test.js:131:3 ›  (4s)
  ✓  test/e2e/launch.e2e.test.js:152:3 ›  (4s)
  ✓  test/e2e/launch.e2e.test.js:173:3 ›  (4s)
  ✓  test/e2e/launch.e2e.test.js:194:3 ›  (6s)
  ✓  test/e2e/launch.e2e.test.js:210:3 ›  (4s)
  ✓  test/e2e/launch.e2e.test.js:222:3 ›  (4s)

  Slow test file: test/e2e/launch.e2e.test.js (41s)
  Consider splitting slow test files to speed up parallel execution

  10 passed (41s)
```

**Comment by SgtPooki** [comment]
I was able to install and run the dmg from the action artifact files at the bottom of https://github.com/ipfs/ipfs-desktop/actions/runs/2240299896.

There are a few issues I'm seeing with the application, below is the content from the logs:

```
2022-04-29T10:07:24.871Z info: [meta] logs can be found on /Users/sgtpooki/Library/Application Support/IPFS Desktop
2022-04-29T10:07:29.330Z error: The 'screen' module can't be used before the app 'ready' event
2022-04-29T10:07:29.339Z error: dialog module can only be used after app is ready
2022-04-29T10:07:29.339Z error: dialog module can only be used after app is ready
2022-04-29T10:07:29.339Z error: dialog module can only be used after app is ready
```

Which wasn't occurring with `npm start`. I will work around these errors using the approach mentioned at https://github.com/electron/electron/issues/5897#issuecomment-224174796

**Comment by hacdias** [comment]
@SgtPooki what's the status on this?

**Comment by SgtPooki** [comment]
> @SgtPooki what's the status on this?

I've had to de-prioritize this due to other work, but I plan on picking this back up as time becomes available outside of the kubo-rpc-client work.

**Comment by SgtPooki** [comment]
superseded by https://github.com/ipfs/ipfs-desktop/pull/2378

**Pull request closed without merging**
