### PR TITLE
chore: create enum for ipcMain eventNames

### PR DESCRIPTION
**Pull request by noliveira95**

### CODE REVIEW

**Comment by noliveira95** [comment]
#2115

**Review by noliveira95 — COMMENTED** [review]
edit: change destructured to added curly brackets for callback

**Review by SgtPooki — APPROVED** [review]

**Review by SgtPooki — APPROVED** [review]

**Comment by SgtPooki** [comment]
I changed a few things, and it should be ready to merge if CI passes

**Review by hacdias — APPROVED** [review]
Very nice. Thanks for this. I also renamed the file and put it on the `common` directory to be consistent with the remaining constants. Once CI is green, I will merge.

**Pull request merged**
