### PR TITLE
fix: click on notification after import of files

### LINKED ISSUE #1815: "Add to IPFS" on Windows does not open correct Files path
Small UX bug (ipfs-desktop 0.15.0 on Windows 10):

- Right-click on a file and "Add to IPFS" from context menu works as expected:  A notification is displayed, File import correctly, Correct link is copied to clipboard.
- Notification says that clicking on it will open imported file in webui (Files screen), but clicking on it opens `#/blank` route

**Screenshots**
ipfs_desktop_screenshot_bugreport_imported_files_click_on_notification

This looks like a regression caused by https://github.com/ipfs/ipfs-webui/pull/1259 or a later refactor.

### PR DESCRIPTION
**Pull request by lidel**
This PR aims to fix UX issue and close  #1815, but is bit tricky for me personally as I don't own any Windows box.
Need to figure out how to test this.

## Test case

1. Install IPFS Desktop
2. Right click on a file and "Add to IPFS"
3. Click on the popup displayed by windows

Expected behavior is that Files screen will be opened.

## TODO

- [x] fix the bug on Windows ;-)
- [x] install .exe created by CI and confirm test case above passes

### CODE REVIEW

**Comment by lidel** [comment]
@RubenKelevra  I believe this should fix the issue you reported in #1858 – mind taking https://bafybeia5lt47ozlqw7skx5vje4v7rrnllwb2j4ephg3i6tlhcig624etce.ipfs.dweb.link/IPFS%20Desktop%20Setup%200.16.0.exe for a spin and confirm the issue is gone?

**Comment by RubenKelevra** [comment]
> @RubenKelevra  I believe this should fix the issue you reported in #1858 – mind taking https://bafybeia5lt47ozlqw7skx5vje4v7rrnllwb2j4ephg3i6tlhcig624etce.ipfs.dweb.link/IPFS%20Desktop%20Setup%200.16.0.exe (0.16.0 + patch from this PR) for a spin and confirm the issue is gone?

Yeah sure. Will do that and report back :) 


 I usually don't use windows as well, just got a new device and tried ipfs on it :)

**Comment by RubenKelevra** [comment]
@lidel works for me :)

ipfs_desktop_screenshot_bugreport_imported_files_click_on_notification_fix

**Comment by RubenKelevra** [comment]
> Expected behavior is that Files screen will be opened.

Well, not exactly. the file itself will be opened, not the "files screen".

**Pull request merged**
